name: Deploy to S3

on:
 
  push:
    branches: [ master ]
permissions:
  id-token: write
  contents: read

jobs:
  build:
    
    name: Build Image
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          role-to-assume: arn:aws:iam::286281612134:role/Saad-OIDC-test
          aws-region: us-east-1

    - name: Installing requirements
      run : |
          pip install os
          pip install GitPython
          pip install markdown
          pip install py_gfm
          pip install pytest-shutil
   
    - name: Build
      run: |
        cd website && python generate.py
        
    - name: Deploy to s3
      run: |
        cd website
        aws s3 sync build/ s3://pearl-ai-dev-frontend-002/
        aws cloudfront create-invalidation --distribution-id E3GI755NHSP5LI --paths '/*'
